kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: deployer-role-dev
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "deployments", "serviceaccounts","services"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: qa
  name: deployer-role-qa
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "deployments", "serviceaccounts", "services"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
