apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: 07-github-el
spec:
  triggers:
    - triggerRef: 07-github-trigger
  serviceAccountName: tekton-triggers-example-sa
---
apiVersion: v1
kind: Service
metadata:
  name: lb-tekton-event-listener-service
spec:
  selector:
    eventlistener: 07-github-el
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
